#
#  Copyright 2023 Paul Guyot <pguyot@kallisys.net>
#
#  SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later
#

name: "Build and publish site"

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: erlang:26
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          rebar3 eunit
      - name: Build
        run: |
          # build avm
          rebar3 packbeam -i -p -s init
          # copy it to html/bin
          cp _build/default/lib/sudoku.avm html/bin/
          # Download AtomVM & libs
          cd html/bin
          wget https://github.com/pguyot/AtomVM/releases/download/246358e/AtomVM.js
          wget https://github.com/pguyot/AtomVM/releases/download/246358e/AtomVM.worker.js
          wget https://github.com/pguyot/AtomVM/releases/download/246358e/AtomVM.wasm
          wget https://github.com/pguyot/AtomVM/releases/download/246358e/atomvmlib.avm
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: html
          retention-days: 1
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: site
          path: html
      - name: Deploy to netlify
        run: |
          docker container run \
           -e NETLIFY_AUTH_TOKEN=$NETLIFY_AUTH_TOKEN \
           -e NETLIFY_SITE_ID=$NETLIFY_SITE_ID \
           -v ${PWD}:/project \
           ghcr.io/williamjacksn/netlify-cli \
           deploy --dir=html --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
